@startuml classes

package src <<Rectangle>> {
    package detection <<Rectangle>> {
        class Landmark {
            - face_detector
            - landmark_detector
            - points
            - init()
            + detect()
            + extract_features()
            + extract_features_img()
            + draw()
        }
        class ViolaJones {
            - cascade
            - init()
            + detect()
        }
    }

    package recognition <<Rectangle>> {
        class SVM {
            - type
            - kernel
            - degree 
            - init()
            + train_svm()
            + predict()
            + load()
        }
    }

    package utils <<Rectangle>> {
        class Utils {
            - init()
            + play()
            + draw_bboxes_video()
            + draw_landmarks_video()
            + get_valences_landmarks_video()
            + online_violajones()
            + online_landmark()
        }
    }
}

package demo.demo <<Rectangle>> {
    class Demo {
        - violajones
        - landmark
        - recognition
        - init()
        + exec()
    }
}

detection -[hidden]-> utils
detection -[hidden]-> recognition
'detection -[hidden]-> demo.demo
@enduml